name: Build ArrowsGO

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install 3DS dependencies
        run: |
          dkp-pacman -Syuu --noconfirm
          dkp-pacman -S --noconfirm 3ds-dev

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ArrowsGO-3dsx
          path: "Arrows GO/ArrowsGO.3dsx"
          if-no-files-found: error
